// <auto-generated />
using System;
using ConsoleApp5.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp5.Migrations
{
    [DbContext(typeof(GoodsContext))]
    partial class GoodsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("ConsoleApp5.DB.Category", b =>
                {
                    b.Property<Guid>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            IdCategory = new Guid("8e19db02-c3d2-4007-859b-319ef103f1bb"),
                            Name = "Овощи"
                        },
                        new
                        {
                            IdCategory = new Guid("6da82f7b-6b84-438c-8451-86352728709b"),
                            Name = "Фрукты"
                        });
                });

            modelBuilder.Entity("ConsoleApp5.DB.Good", b =>
                {
                    b.Property<Guid>("IdGood")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryIdCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Sale")
                        .HasColumnType("REAL");

                    b.HasKey("IdGood");

                    b.HasIndex("CategoryIdCategory");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("ConsoleApp5.DB.Good", b =>
                {
                    b.HasOne("ConsoleApp5.DB.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryIdCategory");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
